#+TITLE: Kprofiles

* Table of contents
:PROPERTIES:
:TOC:
:END:
:CONTENTS:
- [[#about][About]]
- [[#supported-kernel-versions][Supported Kernel Versions]]
- [[#usage][Usage]]
- [[#purpose][Purpose]]
- [[#implementations][Implementations]]
- [[#credits][Credits]]
- [[#how-to-contribute][How To Contribute]]
- [[#license][License]]
- [[#credits][Credits]]
:END:

* About

A kernelspace profiles mode manager that has 4 major modes called *Normal*, *Battery*, *Balanced*, and *Performance*. This driver is a sysfs switch in which a user can simply switch up the currently used profile to a different one by either manually changing the mode number in the node by =echo <number> > /sys/module/kprofiles/parameters/mode=.

* Supported Kernel Versions

Currently 4.9 and 4.14 fully supports kprofiles, look at [[#how-to-contribute][How To Contribute]] if you plan to add support for newer / older kernel versions.

* Usage

** Fetch this repository by this command according to your kernel version

#+BEGIN_SRC shell
git fetch https://github.com/Dakkshesh07/Kprofiles <kernel version>
#+END_SRC

** Apply all commits relevant to kprofiles according to your kernel version, pick the implementations and implement it in some parts on your own aswell and enable it in defconfig with this config option =CONFIG_KPROFILES= then compile

* Purpose

+ To achieve balancing in terms of battery backup and performance.

+ To not apply boosts when the screen is off with display notifiers.

* Implementations

+ kprofiles can be implemented in various places like for example boosting drivers, below is an example of an implementation of kprofiles in kernel/fork.c for zygote forking.

#+BEGIN_SRC diff
-	/* Boost DDR bus to the max for 50 ms when userspace launches an app */
-	if (task_is_zygote(current))
-		devfreq_boost_kick_max(DEVFREQ_MSM_CPUBW, 50);
+	/* Boost DDR bus to the max when userspace launches an app according to set kernel profile */
+	if (task_is_zygote(current) && active_mode() == 0) {
+	  devfreq_boost_kick_max(DEVFREQ_MSM_CPUBW, 15);
+	} else if (task_is_zygote(current) && (active_mode() == 2)) {
+	  devfreq_boost_kick_max(DEVFREQ_MSM_CPUBW, 25);
+	} else if (task_is_zygote(current) && (active_mode() == 3)) {
+	  devfreq_boost_kick_max(DEVFREQ_MSM_CPUBW, 50);
+	} else if (task_is_zygote(current) && (active_mode() == 1)) {
+	  pr_info("Battery profile detected! Skipping DDR bus boost...\n");
+	}
#+END_SRC
[[https://github.com/cyberknight777/dragonheart_kernel_oneplus_sm8150/commit/491d4093686ca09e5ac4c557f6a8c8dea6419a1a][commit]]

+ Have a look at our implementations in our [[https://github.com/dakkshesh07/kprofiles/commits/usage-4.9][4.9 usage]] and [[https://github.com/dakkshesh07/kprofiles/commits/usage-4.14][4.14 usage]] branches.

* How To Contribute

Well you can fork our repo, add your changes / add a new branch, and make a PR to us with the changes (changes with proper explanations ofc).

* License

This project is licensed under GPL-2.0.

* Credits

+ [[https://t.me/Dakkshesh07][Dakkshesh]] for developing kprofiles
+ [[https://t.me/cyberknight777][cyberknight777]] for working together with Dakkshesh on kprofiles fixing issues, pointing out bugs, adding useful implementations and such
+ Some others who helped alongside to develop kprofiles
